apiVersion: v2
name: keycloak
description: A simple Helm chart for Kubernetes
type: application
version: 24.4.11
appVersion: 26.1.3

dependencies:
  - name: common
    version: "2.28.0" # Specify the version of your common chart
    repository: "file://common"