{
 "title": "Keycloak Metrics Dashboard - final",
 "description": "Dashboard of Keycloak metrics exported with Keycloak Metrics SPIhttps://github.com/aerogear/keycloak-metrics-spi",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(keycloak_logins_total,pod)"
    }
   },
   {
    "name": "ClientId",
    "label": "ClientId",
    "query": {
     "query": "label_values(keycloak_logins_total{realm=\"$realm\"},client_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage By Pod ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"keycloak-client\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage By Pod ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"keycloak-client\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx and 5xx Responses all instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(resource) (increase(keycloak_response_errors_total[30m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Registrations Per CLIENT for past 24h",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(client_id) (increase(keycloak_registrations_total[24h]))",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Registrations Per REALM for past 24h all instances",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(realm) (increase(keycloak_registrations_total[24h]))",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Logins Per CLIENT for past 24h all instances",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(client_id) (increase(keycloak_logins_total[24h]))",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Logins per REALM all instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(realm) (increase(keycloak_logins_total[30m]))",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Logins per CLIENT on realm $realm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (client_id)(increase(keycloak_logins_total{realm=\"$realm\"}[30m]))",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Failed Login on realm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (realm) (increase(keycloak_failed_login_attempts_total[30m]))",
     "legendFormat": "{{$realm }} {{error}}"
    }
   ]
  },
  {
   "title": "Registrations per REALM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(realm) (increase(keycloak_registrations_total[30m]))",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Registration Errors on realm $realm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (realm) (increase(keycloak_registrations_errors_total{realm=\"$realm\"} [30m]))",
     "legendFormat": "Sum by {{realm}}"
    },
    {
     "expr": "sum by (error) (increase(keycloak_registrations_errors_total{realm=\"$realm\"} [30m]))",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Registrations per CLIENT on realm $realm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (client_id)(increase(keycloak_registrations_total{realm=\"$realm\"}[30m]))",
     "legendFormat": "{{client_id}}"
    },
    {
     "expr": "sum by (realm)(increase(keycloak_registrations_total{realm=\"$realm\"} [30m]))",
     "legendFormat": "Sum by {{realm}}"
    }
   ]
  },
  {
   "title": "Login Errors for $ClientId",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (error) (increase(keycloak_failed_login_attempts_total{realm=\"$realm\",client_id=\"$ClientId\"}[30m]))",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Request duration method = \"GET\" Heatmap all instances",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by(le) (increase(keycloak_request_duration_bucket{method=\"GET\"}[30m]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Registration Errors for $ClientId",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (error) (increase(keycloak_registrations_errors_total{realm=\"$realm\",client_id=\"$ClientId\"}[30m]))",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Request duration method = \"POST\" Heatmap all instances",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum by(le) (increase(keycloak_request_duration_bucket{method=\"POST\"}[30m]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentage of requests \"GET\"  method  was served in 100ms or below all instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(keycloak_request_duration_bucket{method=\"GET\", le=\"100.0\"}[30m])) * 100) / sum(rate(keycloak_request_duration_count{method=\"GET\"}[30m]))"
    }
   ]
  },
  {
   "title": "Request duration method = \"HEAD\" Heatmap all instances",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum by(le) (increase(keycloak_request_duration_bucket{method=\"HEAD\"}[30m]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentage of requests \"POST\"  method  was served in 100ms or below all instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(keycloak_request_duration_bucket{method=\"POST\", le=\"100.0\"}[30m])) * 100) / sum(rate(keycloak_request_duration_count{method=\"POST\"}[30m]))"
    }
   ]
  },
  {
   "title": "Request duration method = \"PUT\" Heatmap all instances",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum by(le) (increase(keycloak_request_duration_bucket{method=\"PUT\"}[30m]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentage of requests \"HEAD\"  method  was served in 100ms or below all instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(keycloak_request_duration_bucket{method=\"HEAD\", le=\"100.0\"}[30m])) * 100) / sum(rate(keycloak_request_duration_count{method=\"HEAD\"}[30m]))"
    }
   ]
  },
  {
   "title": "Percentage of requests \"PUT\"  method  was served in 100ms or below all instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(keycloak_request_duration_bucket{method=\"PUT\", le=\"100.0\"}[30m])) * 100) / sum(rate(keycloak_request_duration_count{method=\"PUT\"}[30m]))"
    }
   ]
  }
 ]
}