#https://github.com/aws-samples/karpenter-blueprints/blob/main/cluster/terraform/karpenter.tf
#https://github.com/aws/karpenter-provider-aws/tree/main/examples
#https://github.com/aws/karpenter/

apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms: 
  - alias: al2@latest
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        encrypted: true  
  role: "AmazonEKSNodeRole-prod" # replace with your cluster name-
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks_cluster_prod" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks_cluster_prod" # replace with your cluster name
  tags:
    IntentLabel: apps
    KarpenterNodePoolName: default
    NodeType: default
    intent: apps
    karpenter.sh/discovery: eks_cluster_prod
    project: karpenter-blueprints        