
#A Certificate resource should be created to ensure an up to date and signed x509 certificate is stored in the Kubernetes Secret resource named in spec.secretName. certificate generation per namespace
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-certificate
spec:
  secretName: letsencrypt-cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-clusterissuer
  duration: 2160h # 90d
  renewBefore: 360h # 15d before SSL will expire, renew it
  dnsNames:
    - "*.ingotbrokers.dev"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ""    